[package]
name = "soundcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"
reqwest = "0.11"
rodio = "0.17.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"